/*
  # Comprehensive Sample Data for Adnivio Platform

  1. Sample Categories and Products
  2. Sample Investment Profiles
  3. Sample Chat Data
  4. Sample Analytics Data
  5. Sample Coupons and Shipping
*/

-- Insert comprehensive categories
INSERT INTO categories (id, name, slug, description, image_url, is_active) VALUES
  ('cat-electronics', 'Electronics', 'electronics', 'Electronic devices and gadgets', 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg', true),
  ('cat-fashion', 'Fashion', 'fashion', 'Clothing and accessories', 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg', true),
  ('cat-health', 'Health & Wellness', 'health-wellness', 'Health and wellness products', 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),
  ('cat-home', 'Home & Garden', 'home-garden', 'Home decor and garden items', 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg', true),
  ('cat-books', 'Books & Media', 'books-media', 'Books, movies, and media', 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg', true),
  ('cat-sports', 'Sports & Fitness', 'sports-fitness', 'Sports equipment and fitness gear', 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg', true),
  ('cat-automotive', 'Automotive', 'automotive', 'Car accessories and parts', 'https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg', true),
  ('cat-beauty', 'Beauty & Personal Care', 'beauty-personal-care', 'Beauty and personal care products', 'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg', true);

-- Insert subcategories
INSERT INTO categories (id, name, slug, description, parent_id, is_active) VALUES
  ('subcat-smartphones', 'Smartphones', 'smartphones', 'Mobile phones and accessories', 'cat-electronics', true),
  ('subcat-laptops', 'Laptops', 'laptops', 'Laptops and computers', 'cat-electronics', true),
  ('subcat-audio', 'Audio', 'audio', 'Headphones and speakers', 'cat-electronics', true),
  ('subcat-mens-clothing', 'Men''s Clothing', 'mens-clothing', 'Clothing for men', 'cat-fashion', true),
  ('subcat-womens-clothing', 'Women''s Clothing', 'womens-clothing', 'Clothing for women', 'cat-fashion', true),
  ('subcat-supplements', 'Supplements', 'supplements', 'Health supplements', 'cat-health', true),
  ('subcat-fitness', 'Fitness Equipment', 'fitness-equipment', 'Home fitness equipment', 'cat-health', true);

-- Sample shipping zones and rates (these would be created by sellers)
-- Note: These are examples and would typically be created through the application

-- Sample coupons (these would be created by sellers)
-- Note: These are examples and would typically be created through the application

-- Sample analytics events structure (these would be generated by user interactions)
-- Note: Analytics data would be generated automatically by the application

-- Sample notifications structure (these would be generated by system events)
-- Note: Notifications would be created automatically by triggers and application logic

-- The actual sample data for users, products, orders, etc. would be created
-- through the application interface when users register and interact with the platform
-- This ensures proper authentication and RLS policy compliance