/*
  # Comprehensive Sample Data for Adnivio Platform

  1. Sample Categories and Products
  2. Sample Investment Profiles
  3. Sample Chat Data
  4. Sample Analytics Data
  5. Sample Coupons and Shipping
*/

-- Insert comprehensive categories
INSERT INTO categories (id, name, slug, description, image_url, is_active) VALUES
  ('a1111111-1111-1111-1111-111111111111', 'Electronics', 'electronics', 'Electronic devices and gadgets', 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg', true),
  ('a2222222-2222-2222-2222-222222222222', 'Fashion', 'fashion', 'Clothing and accessories', 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg', true),
  ('a3333333-3333-3333-3333-333333333333', 'Health & Wellness', 'health-wellness', 'Health and wellness products', 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),
  ('a4444444-4444-4444-4444-444444444444', 'Home & Garden', 'home-garden', 'Home decor and garden items', 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg', true),
  ('a5555555-5555-5555-5555-555555555555', 'Books & Media', 'books-media', 'Books, movies, and media', 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg', true),
  ('a6666666-6666-6666-6666-666666666666', 'Sports & Fitness', 'sports-fitness', 'Sports equipment and fitness gear', 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg', true),
  ('a7777777-7777-7777-7777-777777777777', 'Automotive', 'automotive', 'Car accessories and parts', 'https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg', true),
  ('a8888888-8888-8888-8888-888888888888', 'Beauty & Personal Care', 'beauty-personal-care', 'Beauty and personal care products', 'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg', true)
ON CONFLICT (id) DO NOTHING;

-- Insert subcategories
INSERT INTO categories (id, name, slug, description, parent_id, is_active) VALUES
  ('b1111111-1111-1111-1111-111111111111', 'Smartphones', 'smartphones', 'Mobile phones and accessories', 'a1111111-1111-1111-1111-111111111111', true),
  ('b2222222-2222-2222-2222-222222222222', 'Laptops', 'laptops', 'Laptops and computers', 'a1111111-1111-1111-1111-111111111111', true),
  ('b3333333-3333-3333-3333-333333333333', 'Audio', 'audio', 'Headphones and speakers', 'a1111111-1111-1111-1111-111111111111', true),
  ('b4444444-4444-4444-4444-444444444444', 'Men''s Clothing', 'mens-clothing', 'Clothing for men', 'a2222222-2222-2222-2222-222222222222', true),
  ('b5555555-5555-5555-5555-555555555555', 'Women''s Clothing', 'womens-clothing', 'Clothing for women', 'a2222222-2222-2222-2222-222222222222', true),
  ('b6666666-6666-6666-6666-666666666666', 'Supplements', 'supplements', 'Health supplements', 'a3333333-3333-3333-3333-333333333333', true),
  ('b7777777-7777-7777-7777-777777777777', 'Fitness Equipment', 'fitness-equipment', 'Home fitness equipment', 'a3333333-3333-3333-3333-333333333333', true)
ON CONFLICT (id) DO NOTHING;

-- Sample shipping zones and rates (these would be created by sellers)
-- Note: These are examples and would typically be created through the application

-- Sample coupons (these would be created by sellers)
-- Note: These are examples and would typically be created through the application

-- Sample analytics events structure (these would be generated by user interactions)
-- Note: Analytics data would be generated automatically by the application

-- Sample notifications structure (these would be generated by system events)
-- Note: Notifications would be created automatically by triggers and application logic

-- The actual sample data for users, products, orders, etc. would be created
-- through the application interface when users register and interact with the platform
-- This ensures proper authentication and RLS policy compliance